// Vite+ per-package settings, mirroring packages/custom-gatekeeper/vite.config.ts.
//
// `build` and `test` are tasks rather than package.json scripts because each reads a path it also
// writes, and vp declines to cache such a task: `tsc` emits into `dist/`, which automatic tracking
// otherwise counts as an input of the same package. vp forbids a task and a script sharing a name,
// so there are no `build`/`test` scripts -- `vp run -F gatekeeper-microsoft <task>` replaces them.

// This package's own `tsc` output. Package-relative, not workspace-wide: a sibling's `dist/` may be
// a real input via its `exports`.
const ownDist = { pattern: '!dist/**', base: 'package' } as const

// Written and read back by every vitest run, so without these almost nothing caches.
const vitestScratch = [
  { pattern: '!**/node_modules/.vite/**', base: 'workspace' },
  { pattern: '!**/node_modules/.vite-temp/**', base: 'workspace' },
  // The capnweb-validate build tree, regenerated by any suite that starts a worker under
  // @cloudflare/vitest-pool-workers. Derived from tracked sources, so dropping it loses nothing.
  { pattern: '!**/.wrangler/**', base: 'workspace' },
] as const

export default {
  run: {
    tasks: {
      build: {
        command: 'tsc',
        input: [{ auto: true }, ownDist],
        output: ['dist/**'],
      },
      test: {
        command: 'vitest run',
        input: [{ auto: true }, ownDist, ...vitestScratch],
        output: [{ auto: true }, ownDist, ...vitestScratch],
      },
    },
  },
}
